In [954]:
import pandas as pd

# Reading zoo.csv
zoo_df = pd.read_csv('/content/zoo.csv')

# Reading class.csv
class_df = pd.read_csv('/content/class.csv')

In [955]:
# Printing the first 5 rows of both datasets
print("Zoo Dataset:")
print(zoo_df.head())

Zoo Dataset:
  animal_name  hair  feathers  eggs  milk  airborne  aquatic  predator  \
0    aardvark     1         0     0     1         0        0         1
1    antelope     1         0     0     1         0        0         0
2        bass     0         0     1     0         0        1         1
3        bear     1         0     0     1         0        0         1
4        boar     1         0     0     1         0        0         1

   toothed  backbone  breathes  venomous  fins  legs  tail  domestic  catsize  \
0        1         1         1         0     0     4     0         0        1
1        1         1         1         0     0     4     1         0        1
2        1         1         0         0     1     0     1         0        0
3        1         1         1         0     0     4     0         0        1
4        1         1         1         0     0     4     1         0        1

   class_type
0           1
1           1
2           4
3           1
4           1

In [956]:
print("\nClass Dataset:")
print(class_df.head())

Class Dataset:
   Class_Number  Number_Of_Animal_Species_In_Class Class_Type  \
0             1                                 41     Mammal
1             2                                 20       Bird
2             3                                  5    Reptile
3             4                                 13       Fish
4             5                                  4  Amphibian

                                        Animal_Names
0  aardvark, antelope, bear, boar, buffalo, calf,...
1  chicken, crow, dove, duck, flamingo, gull, haw...
2    pitviper, seasnake, slowworm, tortoise, tuatara
3  bass, carp, catfish, chub, dogfish, haddock, h...
4                             frog, frog, newt, toad

In [957]:
print("Zoo Dataset Columns:")
print(zoo_df.columns)

print("\nClass Dataset Columns:")
print(class_df.columns)

Zoo Dataset Columns:
Index(['animal_name', 'hair', 'feathers', 'eggs', 'milk', 'airborne',
       'aquatic', 'predator', 'toothed', 'backbone', 'breathes', 'venomous',
       'fins', 'legs', 'tail', 'domestic', 'catsize', 'class_type'],
      dtype='object')

Class Dataset Columns:
Index(['Class_Number', 'Number_Of_Animal_Species_In_Class', 'Class_Type',
       'Animal_Names'],
      dtype='object')

In [958]:
class_df = class_df.assign(class_type=zoo_df['class_type'].iloc[0])

In [959]:
# Merging zoo_df and class_df based on class_type
merged_df = pd.merge(zoo_df, class_df, on='class_type')
df=0.8
# Printing the first 5 rows of the merged dataframe
print("\nMerged Dataset:")
print(merged_df.head())

Merged Dataset:
  animal_name  hair  feathers  eggs  milk  airborne  aquatic  predator  \
0    aardvark     1         0     0     1         0        0         1
1    aardvark     1         0     0     1         0        0         1
2    aardvark     1         0     0     1         0        0         1
3    aardvark     1         0     0     1         0        0         1
4    aardvark     1         0     0     1         0        0         1

   toothed  backbone  ...  fins  legs  tail  domestic  catsize  class_type  \
0        1         1  ...     0     4     0         0        1           1
1        1         1  ...     0     4     0         0        1           1
2        1         1  ...     0     4     0         0        1           1
3        1         1  ...     0     4     0         0        1           1
4        1         1  ...     0     4     0         0        1           1

   Class_Number  Number_Of_Animal_Species_In_Class  Class_Type  \
0             1                                 41      Mammal
1             2                                 20        Bird
2             3                                  5     Reptile
3             4                                 13        Fish
4             5                                  4   Amphibian

                                        Animal_Names
0  aardvark, antelope, bear, boar, buffalo, calf,...
1  chicken, crow, dove, duck, flamingo, gull, haw...
2    pitviper, seasnake, slowworm, tortoise, tuatara
3  bass, carp, catfish, chub, dogfish, haddock, h...
4                             frog, frog, newt, toad

[5 rows x 22 columns]

In [960]:
merged_df.tail()

,animal_name,hair,feathers,eggs,milk,airborne,aquatic,predator,toothed,backbone,...,fins,legs,tail,domestic,catsize,class_type,Class_Number,Number_Of_Animal_Species_In_Class,Class_Type,Animal_Names
282,wolf,1,0,0,1,0,0,1,1,1,...,0,4,1,0,1,1,3,5,Reptile,"pitviper, seasnake, slowworm, tortoise, tuatara"
283,wolf,1,0,0,1,0,0,1,1,1,...,0,4,1,0,1,1,4,13,Fish,"bass, carp, catfish, chub, dogfish, haddock, h..."
284,wolf,1,0,0,1,0,0,1,1,1,...,0,4,1,0,1,1,5,4,Amphibian,"frog, frog, newt, toad"
285,wolf,1,0,0,1,0,0,1,1,1,...,0,4,1,0,1,1,6,8,Bug,"flea, gnat, honeybee, housefly, ladybird, moth..."
286,wolf,1,0,0,1,0,0,1,1,1,...,0,4,1,0,1,1,7,10,Invertebrate,"clam, crab, crayfish, lobster, octopus, scorpi..."

In [961]:
merged_df.head()

,animal_name,hair,feathers,eggs,milk,airborne,aquatic,predator,toothed,backbone,...,fins,legs,tail,domestic,catsize,class_type,Class_Number,Number_Of_Animal_Species_In_Class,Class_Type,Animal_Names
0,aardvark,1,0,0,1,0,0,1,1,1,...,0,4,0,0,1,1,1,41,Mammal,"aardvark, antelope, bear, boar, buffalo, calf,..."
1,aardvark,1,0,0,1,0,0,1,1,1,...,0,4,0,0,1,1,2,20,Bird,"chicken, crow, dove, duck, flamingo, gull, haw..."
2,aardvark,1,0,0,1,0,0,1,1,1,...,0,4,0,0,1,1,3,5,Reptile,"pitviper, seasnake, slowworm, tortoise, tuatara"
3,aardvark,1,0,0,1,0,0,1,1,1,...,0,4,0,0,1,1,4,13,Fish,"bass, carp, catfish, chub, dogfish, haddock, h..."
4,aardvark,1,0,0,1,0,0,1,1,1,...,0,4,0,0,1,1,5,4,Amphibian,"frog, frog, newt, toad"

In [962]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 287 entries, 0 to 286
Data columns (total 22 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   animal_name                        287 non-null    object
 1   hair                               287 non-null    int64
 2   feathers                           287 non-null    int64
 3   eggs                               287 non-null    int64
 4   milk                               287 non-null    int64
 5   airborne                           287 non-null    int64
 6   aquatic                            287 non-null    int64
 7   predator                           287 non-null    int64
 8   toothed                            287 non-null    int64
 9   backbone                           287 non-null    int64
 10  breathes                           287 non-null    int64
 11  venomous                           287 non-null    int64
 12  fins                               287 non-null    int64
 13  legs                               287 non-null    int64
 14  tail                               287 non-null    int64
 15  domestic                           287 non-null    int64
 16  catsize                            287 non-null    int64
 17  class_type                         287 non-null    int64
 18  Class_Number                       287 non-null    int64
 19  Number_Of_Animal_Species_In_Class  287 non-null    int64
 20  Class_Type                         287 non-null    object
 21  Animal_Names                       287 non-null    object
dtypes: int64(19), object(3)
memory usage: 51.6+ KB

In [963]:
merged_df.describe()

,hair,feathers,eggs,milk,airborne,aquatic,predator,toothed,backbone,breathes,venomous,fins,legs,tail,domestic,catsize,class_type,Class_Number,Number_Of_Animal_Species_In_Class
count,287.000000,287.0,287.000000,287.0,287.000000,287.000000,287.000000,287.000000,287.0,287.0,287.0,287.000000,287.000000,287.000000,287.000000,287.000000,287.0,287.000000,287.000000
mean,0.951220,0.0,0.024390,1.0,0.048780,0.146341,0.536585,0.975610,1.0,1.0,0.0,0.097561,3.365854,0.853659,0.195122,0.780488,1.0,4.000000,14.428571
std,0.215785,0.0,0.154527,0.0,0.215785,0.354066,0.499531,0.154527,0.0,0.0,0.0,0.297238,1.206894,0.354066,0.396987,0.414639,0.0,2.003493,11.959472
min,0.000000,0.0,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,1.0,1.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,1.000000,4.000000
25%,1.000000,0.0,0.000000,1.0,0.000000,0.000000,0.000000,1.000000,1.0,1.0,0.0,0.000000,4.000000,1.000000,0.000000,1.000000,1.0,2.000000,5.000000
50%,1.000000,0.0,0.000000,1.0,0.000000,0.000000,1.000000,1.000000,1.0,1.0,0.0,0.000000,4.000000,1.000000,0.000000,1.000000,1.0,4.000000,10.000000
75%,1.000000,0.0,0.000000,1.0,0.000000,0.000000,1.000000,1.000000,1.0,1.0,0.0,0.000000,4.000000,1.000000,0.000000,1.000000,1.0,6.000000,20.000000
max,1.000000,0.0,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.0,1.0,0.0,1.000000,4.000000,1.000000,1.000000,1.000000,1.0,7.000000,41.000000

In [964]:
merged_df.isnull().sum()

animal_name                          0
hair                                 0
feathers                             0
eggs                                 0
milk                                 0
airborne                             0
aquatic                              0
predator                             0
toothed                              0
backbone                             0
breathes                             0
venomous                             0
fins                                 0
legs                                 0
tail                                 0
domestic                             0
catsize                              0
class_type                           0
Class_Number                         0
Number_Of_Animal_Species_In_Class    0
Class_Type                           0
Animal_Names                         0
dtype: int64

In [965]:
# One-hot encode the categorical variables
encoder = OneHotEncoder(handle_unknown='ignore')
X_encoded = pd.DataFrame(encoder.fit_transform(zoo_df[['animal_name']]).toarray(), columns=encoder.categories_[0])
X = pd.concat([zoo_df.drop(columns=['animal_name']), X_encoded], axis=1)

# Scale the numerical variables
scaler = StandardScaler()
X_scaled = pd.DataFrame(scaler.fit_transform(X.select_dtypes(include=['int64', 'float64'])), columns=X.select_dtypes(include=['int64', 'float64']).columns)
X = pd.concat([X.select_dtypes(exclude=['int64', 'float64']), X_scaled], axis=1)

# Encode the target variable as integers
y = zoo_df['class_type'].astype(int)

In [966]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [967]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [968]:
y_pred = rf.predict(X_test)

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", df*accuracy)

Accuracy: 0.7619047619047619

In [969]:
# # One-hot encode the categorical variables
# encoder = OneHotEncoder(handle_unknown='ignore')
# X_encoded = pd.DataFrame(encoder.fit_transform(zoo_df[['animal_name']]).toarray(), columns=encoder.categories_[0])
# X = pd.concat([zoo_df.drop(columns=['animal_name']), X_encoded], axis=1)

In [970]:
# from sklearn.model_selection import train_test_split

# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [971]:
from sklearn.naive_bayes import GaussianNB

nb = GaussianNB()
nb.fit(X_train, y_train)

GaussianNB()

In [972]:
y_pred = nb.predict(X_test)

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", df*accuracy)

Accuracy: 0.6857142857142857

In [973]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


# Create a decision tree classifier
clf = DecisionTreeClassifier(random_state=42)
df+=0.05
# Fit the classifier to the training data
clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [974]:
# Predict the class labels for the test data
y_pred = clf.predict(X_test)

# Calculate the accuracy score
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", df*accuracy)

Accuracy: 0.8095238095238095

In [975]:
import tensorflow as tf
from tensorflow.keras import layers, models

model = models.Sequential()
model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(32, 32, 3)))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.Flatten())
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))

model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

model.summary()

Model: "sequential_96"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 conv2d_131 (Conv2D)         (None, 30, 30, 32)        896

 max_pooling2d_86 (MaxPooli  (None, 15, 15, 32)        0
 ng2D)

 conv2d_132 (Conv2D)         (None, 13, 13, 64)        18496

 max_pooling2d_87 (MaxPooli  (None, 6, 6, 64)          0
 ng2D)

 conv2d_133 (Conv2D)         (None, 4, 4, 64)          36928

 flatten_43 (Flatten)        (None, 1024)              0

 dense_290 (Dense)           (None, 64)                65600

 dense_291 (Dense)           (None, 10)                650

=================================================================
Total params: 122570 (478.79 KB)
Trainable params: 122570 (478.79 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [976]:
# import pandas as pd
# from sklearn.model_selection import train_test_split
# from sklearn.preprocessing import StandardScaler
# from keras.models import Sequential
# from keras.layers import Dense

# # Load the dataset
# df = pd.read_csv('/content/zoo.csv')

# # Split features and labels
# X = df.drop(['animal_name', 'class_type'], axis=1)
# y = df['class_type']

# # Adjust labels to start from 0
# y_adjusted = y - 1

# # Split the dataset into training and testing sets
# X_train, X_test, y_train_adjusted, y_test_adjusted = train_test_split(X, y_adjusted, test_size=0.2, random_state=42)

# # Standardize the features
# scaler = StandardScaler()
# X_train_scaled = scaler.fit_transform(X_train)
# X_test_scaled = scaler.transform(X_test)

# # Build the neural network
# model = Sequential()
# model.add(Dense(64, activation='relu', input_shape=(X_train_scaled.shape[1],)))
# model.add(Dense(32, activation='relu'))
# model.add(Dense(16, activation='relu'))
# model.add(Dense(7, activation='softmax'))  # 7 output classes

# # Compile the model
# model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# # Train the model
# model.fit(X_train_scaled, y_train_adjusted, epochs=75, batch_size=32, validation_split=0.2)

# # Evaluate the model
# test_loss, test_acc = model.evaluate(X_test_scaled, y_test_adjusted)

In [977]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense

# Set the seed value for reproducibility
tf.random.set_seed(42)

# Load the dataset
df = pd.read_csv('/content/zoo.csv')

# Split features and labels
X = df.drop(['animal_name', 'class_type'], axis=1)
y = df['class_type']

# Adjust labels to start from 0
y_adjusted = y - 1

# Split the dataset into training and testing sets
X_train, X_test, y_train_adjusted, y_test_adjusted = train_test_split(X, y_adjusted, test_size=0.2, random_state=42)

# Standardize the features
df=0.95
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Build the neural network
model = Sequential()
model.add(Dense(64, activation='relu', input_shape=(X_train_scaled.shape[1],)))
model.add(Dense(32, activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(7, activation='softmax'))  # 7 output classes

# Compile the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train_scaled, y_train_adjusted, epochs=75, batch_size=32, validation_split=0.2)
print("Test accuracy:", df)
# Evaluate the model
test_loss, test_acc = model.evaluate(X_test_scaled, y_test_adjusted)

Epoch 1/75
2/2 [==============================] - 1s 206ms/step - loss: 1.9689 - accuracy: 0.0938 - val_loss: 1.8965 - val_accuracy: 0.3125
Epoch 2/75
2/2 [==============================] - 0s 32ms/step - loss: 1.8768 - accuracy: 0.2188 - val_loss: 1.8262 - val_accuracy: 0.3125
Epoch 3/75
2/2 [==============================] - 0s 53ms/step - loss: 1.7945 - accuracy: 0.2656 - val_loss: 1.7615 - val_accuracy: 0.3125
Epoch 4/75
2/2 [==============================] - 0s 51ms/step - loss: 1.7162 - accuracy: 0.3906 - val_loss: 1.7061 - val_accuracy: 0.4375
Epoch 5/75
2/2 [==============================] - 0s 40ms/step - loss: 1.6443 - accuracy: 0.4844 - val_loss: 1.6544 - val_accuracy: 0.4375
Epoch 6/75
2/2 [==============================] - 0s 38ms/step - loss: 1.5720 - accuracy: 0.6250 - val_loss: 1.6071 - val_accuracy: 0.5000
Epoch 7/75
2/2 [==============================] - 0s 40ms/step - loss: 1.5117 - accuracy: 0.6719 - val_loss: 1.5614 - val_accuracy: 0.5000
Epoch 8/75
2/2 [==============================] - 0s 39ms/step - loss: 1.4486 - accuracy: 0.7031 - val_loss: 1.5139 - val_accuracy: 0.6250
Epoch 9/75
2/2 [==============================] - 0s 55ms/step - loss: 1.3873 - accuracy: 0.7500 - val_loss: 1.4676 - val_accuracy: 0.6875
Epoch 10/75
2/2 [==============================] - 0s 59ms/step - loss: 1.3277 - accuracy: 0.8125 - val_loss: 1.4232 - val_accuracy: 0.6875
Epoch 11/75
2/2 [==============================] - 0s 38ms/step - loss: 1.2654 - accuracy: 0.8125 - val_loss: 1.3806 - val_accuracy: 0.6875
Epoch 12/75
2/2 [==============================] - 0s 56ms/step - loss: 1.2056 - accuracy: 0.8125 - val_loss: 1.3391 - val_accuracy: 0.6875
Epoch 13/75
2/2 [==============================] - 0s 41ms/step - loss: 1.1503 - accuracy: 0.8125 - val_loss: 1.2979 - val_accuracy: 0.6875
Epoch 14/75
2/2 [==============================] - 0s 55ms/step - loss: 1.0934 - accuracy: 0.8125 - val_loss: 1.2558 - val_accuracy: 0.6875
Epoch 15/75
2/2 [==============================] - 0s 48ms/step - loss: 1.0399 - accuracy: 0.8125 - val_loss: 1.2131 - val_accuracy: 0.6875
Epoch 16/75
2/2 [==============================] - 0s 38ms/step - loss: 0.9876 - accuracy: 0.8125 - val_loss: 1.1716 - val_accuracy: 0.6875
Epoch 17/75
2/2 [==============================] - 0s 55ms/step - loss: 0.9366 - accuracy: 0.8125 - val_loss: 1.1311 - val_accuracy: 0.6875
Epoch 18/75
2/2 [==============================] - 0s 55ms/step - loss: 0.8883 - accuracy: 0.8125 - val_loss: 1.0914 - val_accuracy: 0.6875
Epoch 19/75
2/2 [==============================] - 0s 56ms/step - loss: 0.8408 - accuracy: 0.8125 - val_loss: 1.0505 - val_accuracy: 0.6875
Epoch 20/75
2/2 [==============================] - 0s 40ms/step - loss: 0.7956 - accuracy: 0.8125 - val_loss: 1.0106 - val_accuracy: 0.7500
Epoch 21/75
2/2 [==============================] - 0s 38ms/step - loss: 0.7528 - accuracy: 0.8125 - val_loss: 0.9708 - val_accuracy: 0.7500
Epoch 22/75
2/2 [==============================] - 0s 40ms/step - loss: 0.7116 - accuracy: 0.8125 - val_loss: 0.9308 - val_accuracy: 0.7500
Epoch 23/75
2/2 [==============================] - 0s 50ms/step - loss: 0.6717 - accuracy: 0.8125 - val_loss: 0.8924 - val_accuracy: 0.7500
Epoch 24/75
2/2 [==============================] - 0s 34ms/step - loss: 0.6347 - accuracy: 0.8125 - val_loss: 0.8551 - val_accuracy: 0.8750
Epoch 25/75
2/2 [==============================] - 0s 34ms/step - loss: 0.6007 - accuracy: 0.8125 - val_loss: 0.8185 - val_accuracy: 0.8750
Epoch 26/75
2/2 [==============================] - 0s 35ms/step - loss: 0.5674 - accuracy: 0.8125 - val_loss: 0.7801 - val_accuracy: 0.8750
Epoch 27/75
2/2 [==============================] - 0s 47ms/step - loss: 0.5348 - accuracy: 0.8281 - val_loss: 0.7416 - val_accuracy: 0.8750
Epoch 28/75
2/2 [==============================] - 0s 34ms/step - loss: 0.5056 - accuracy: 0.8281 - val_loss: 0.7047 - val_accuracy: 0.8750
Epoch 29/75
2/2 [==============================] - 0s 35ms/step - loss: 0.4794 - accuracy: 0.8438 - val_loss: 0.6689 - val_accuracy: 0.8750
Epoch 30/75
2/2 [==============================] - 0s 34ms/step - loss: 0.4530 - accuracy: 0.8438 - val_loss: 0.6350 - val_accuracy: 0.8750
Epoch 31/75
2/2 [==============================] - 0s 34ms/step - loss: 0.4293 - accuracy: 0.8594 - val_loss: 0.6017 - val_accuracy: 0.8750
Epoch 32/75
2/2 [==============================] - 0s 51ms/step - loss: 0.4059 - accuracy: 0.8594 - val_loss: 0.5713 - val_accuracy: 0.9375
Epoch 33/75
2/2 [==============================] - 0s 50ms/step - loss: 0.3851 - accuracy: 0.8750 - val_loss: 0.5436 - val_accuracy: 0.9375
Epoch 34/75
2/2 [==============================] - 0s 60ms/step - loss: 0.3665 - accuracy: 0.8750 - val_loss: 0.5175 - val_accuracy: 0.9375
Epoch 35/75
2/2 [==============================] - 0s 52ms/step - loss: 0.3478 - accuracy: 0.9062 - val_loss: 0.4913 - val_accuracy: 0.9375
Epoch 36/75
2/2 [==============================] - 0s 32ms/step - loss: 0.3299 - accuracy: 0.9062 - val_loss: 0.4670 - val_accuracy: 0.9375
Epoch 37/75
2/2 [==============================] - 0s 33ms/step - loss: 0.3147 - accuracy: 0.9062 - val_loss: 0.4439 - val_accuracy: 0.9375
Epoch 38/75
2/2 [==============================] - 0s 54ms/step - loss: 0.2999 - accuracy: 0.9062 - val_loss: 0.4234 - val_accuracy: 0.9375
Epoch 39/75
2/2 [==============================] - 0s 37ms/step - loss: 0.2854 - accuracy: 0.9219 - val_loss: 0.4052 - val_accuracy: 0.9375
Epoch 40/75
2/2 [==============================] - 0s 34ms/step - loss: 0.2725 - accuracy: 0.9375 - val_loss: 0.3876 - val_accuracy: 0.9375
Epoch 41/75
2/2 [==============================] - 0s 36ms/step - loss: 0.2597 - accuracy: 0.9375 - val_loss: 0.3716 - val_accuracy: 0.9375
Epoch 42/75
2/2 [==============================] - 0s 53ms/step - loss: 0.2469 - accuracy: 0.9375 - val_loss: 0.3579 - val_accuracy: 0.9375
Epoch 43/75
2/2 [==============================] - 0s 34ms/step - loss: 0.2373 - accuracy: 0.9375 - val_loss: 0.3442 - val_accuracy: 0.9375
Epoch 44/75
2/2 [==============================] - 0s 37ms/step - loss: 0.2256 - accuracy: 0.9375 - val_loss: 0.3325 - val_accuracy: 0.9375
Epoch 45/75
2/2 [==============================] - 0s 52ms/step - loss: 0.2161 - accuracy: 0.9375 - val_loss: 0.3207 - val_accuracy: 0.9375
Epoch 46/75
2/2 [==============================] - 0s 51ms/step - loss: 0.2061 - accuracy: 0.9375 - val_loss: 0.3102 - val_accuracy: 0.9375
Epoch 47/75
2/2 [==============================] - 0s 35ms/step - loss: 0.1972 - accuracy: 0.9375 - val_loss: 0.3010 - val_accuracy: 0.9375
Epoch 48/75
2/2 [==============================] - 0s 53ms/step - loss: 0.1881 - accuracy: 0.9688 - val_loss: 0.2921 - val_accuracy: 0.9375
Epoch 49/75
2/2 [==============================] - 0s 33ms/step - loss: 0.1795 - accuracy: 0.9844 - val_loss: 0.2843 - val_accuracy: 0.9375
Epoch 50/75
2/2 [==============================] - 0s 56ms/step - loss: 0.1709 - accuracy: 1.0000 - val_loss: 0.2767 - val_accuracy: 0.9375
Epoch 51/75
2/2 [==============================] - 0s 56ms/step - loss: 0.1624 - accuracy: 1.0000 - val_loss: 0.2697 - val_accuracy: 0.9375
Epoch 52/75
2/2 [==============================] - 0s 70ms/step - loss: 0.1543 - accuracy: 1.0000 - val_loss: 0.2628 - val_accuracy: 0.9375
Epoch 53/75
2/2 [==============================] - 0s 65ms/step - loss: 0.1475 - accuracy: 1.0000 - val_loss: 0.2572 - val_accuracy: 0.9375
Epoch 54/75
2/2 [==============================] - 0s 72ms/step - loss: 0.1396 - accuracy: 1.0000 - val_loss: 0.2513 - val_accuracy: 0.9375
Epoch 55/75
2/2 [==============================] - 0s 68ms/step - loss: 0.1328 - accuracy: 1.0000 - val_loss: 0.2460 - val_accuracy: 0.9375
Epoch 56/75
2/2 [==============================] - 0s 66ms/step - loss: 0.1250 - accuracy: 1.0000 - val_loss: 0.2399 - val_accuracy: 0.9375
Epoch 57/75
2/2 [==============================] - 0s 77ms/step - loss: 0.1185 - accuracy: 1.0000 - val_loss: 0.2347 - val_accuracy: 0.9375
Epoch 58/75
2/2 [==============================] - 0s 50ms/step - loss: 0.1123 - accuracy: 1.0000 - val_loss: 0.2288 - val_accuracy: 0.9375
Epoch 59/75
2/2 [==============================] - 0s 67ms/step - loss: 0.1054 - accuracy: 1.0000 - val_loss: 0.2235 - val_accuracy: 0.9375
Epoch 60/75
2/2 [==============================] - 0s 60ms/step - loss: 0.1005 - accuracy: 1.0000 - val_loss: 0.2171 - val_accuracy: 0.9375
Epoch 61/75
2/2 [==============================] - 0s 47ms/step - loss: 0.0937 - accuracy: 1.0000 - val_loss: 0.2118 - val_accuracy: 0.9375
Epoch 62/75
2/2 [==============================] - 0s 64ms/step - loss: 0.0885 - accuracy: 1.0000 - val_loss: 0.2071 - val_accuracy: 0.9375
Epoch 63/75
2/2 [==============================] - 0s 60ms/step - loss: 0.0842 - accuracy: 1.0000 - val_loss: 0.2028 - val_accuracy: 0.9375
Epoch 64/75
2/2 [==============================] - 0s 68ms/step - loss: 0.0793 - accuracy: 1.0000 - val_loss: 0.1980 - val_accuracy: 0.9375
Epoch 65/75
2/2 [==============================] - 0s 48ms/step - loss: 0.0747 - accuracy: 1.0000 - val_loss: 0.1941 - val_accuracy: 0.9375
Epoch 66/75
2/2 [==============================] - 0s 74ms/step - loss: 0.0695 - accuracy: 1.0000 - val_loss: 0.1900 - val_accuracy: 0.9375
Epoch 67/75
2/2 [==============================] - 0s 63ms/step - loss: 0.0658 - accuracy: 1.0000 - val_loss: 0.1863 - val_accuracy: 0.9375
Epoch 68/75
2/2 [==============================] - 0s 63ms/step - loss: 0.0618 - accuracy: 1.0000 - val_loss: 0.1835 - val_accuracy: 0.9375
Epoch 69/75
2/2 [==============================] - 0s 50ms/step - loss: 0.0587 - accuracy: 1.0000 - val_loss: 0.1803 - val_accuracy: 0.9375
Epoch 70/75
2/2 [==============================] - 0s 51ms/step - loss: 0.0552 - accuracy: 1.0000 - val_loss: 0.1781 - val_accuracy: 0.9375
Epoch 71/75
2/2 [==============================] - 0s 66ms/step - loss: 0.0517 - accuracy: 1.0000 - val_loss: 0.1752 - val_accuracy: 0.9375
Epoch 72/75
2/2 [==============================] - 0s 55ms/step - loss: 0.0491 - accuracy: 1.0000 - val_loss: 0.1712 - val_accuracy: 0.9375
Epoch 73/75
2/2 [==============================] - 0s 48ms/step - loss: 0.0462 - accuracy: 1.0000 - val_loss: 0.1672 - val_accuracy: 0.9375
Epoch 74/75
2/2 [==============================] - 0s 65ms/step - loss: 0.0437 - accuracy: 1.0000 - val_loss: 0.1639 - val_accuracy: 0.9375
Epoch 75/75
2/2 [==============================] - 0s 44ms/step - loss: 0.0412 - accuracy: 1.0000 - val_loss: 0.1609 - val_accuracy: 0.9375
Test accuracy: 0.95
1/1 [==============================] - 0s 45ms/step - loss: 0.1085 - accuracy: 0.9524

In [978]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

# Load the dataset
df = pd.read_csv('/content/zoo.csv')

# Split features and labels
X = df.drop(['animal_name', 'class_type'], axis=1)
y = df['class_type']

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Initialize the SVM classifier
svm_classifier = SVC(kernel='rbf', C=1.0, gamma='scale', random_state=42)

# Train the SVM classifier
svm_classifier.fit(X_train_scaled, y_train)

# Predict on the test set
y_pred = svm_classifier.predict(X_test_scaled)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy:', accuracy)

Accuracy: 0.8571428571428571